require:
  - rubocop-rspec
  - rubocop-rails

Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 50

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/{rails,rake,bundle}'
    - 'config/initializers/{devise.rb}'
    - 'node_modules/**/*'