version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

commands:
  bundler_install:
    description: Install bundler
    steps:
      - run: gem install bundler --version $BUNDLER_VERSION
  database_config:
    description: Configure database file
    steps:
      - run: rm config/database.yml
      - run: cp config/database.ci.yml config/database.yml
  yarn_install:
    description: Install yarn
    steps:
      - run: yarn install
  bundle_install:
    description: Install gems
    steps:
      - bundler_install
      - run: bundle install
  prepare_database:
    description: Prepare database for tests
    steps:
      - database_config
      - run: bundle exec rails db:create
      - run: bundle exec rake db:schema:load
  run_rspec_tests:
    description: Run Rspec unit tests
    steps:
      - run: bundle exec rspec  
jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0-node-browsers
      - image: circleci/postgres:12
        environment:
          POSTGRES_PASSWORD: password
      - image: circleci/redis:6
    environment:
      - BUNDLER_VERSION: 2.2.3
    executor: ruby/default
    steps:
      - checkout
      - bundle_install
      - prepare_database
      - yarn_install
      - run_rspec_tests



      

