version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

commands:
  install_bundler:
    description: Install bundler
    steps:
      - run: gem install bundler --version $BUNDLER_VERSION
  install_yarn:
    description: Install yarn
    steps:
      - run: yarn install
jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0-node-browsers
      - image: circleci/postgres:12
        environment:
          POSTGRES_PASSWORD: password
      - image: circleci/redis:6
    environment:
      - BUNDLER_VERSION: 2.2.3
    executor: ruby/default
    steps:
      - checkout
      - install_bundler
      - install_yarn
